# .github/workflows/build-push-docker.yml

name: Build, Push, and Deploy to EKS

# This workflow runs on pushes to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  # --- Job 1: Build and Push Docker Image (No changes here) ---
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./hello_world/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hello-grainchain:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/hello-grainchain:${{ github.sha }}

  # --- Job 2: Deploy to EKS using Helm (New job) ---
  deploy:
    runs-on: ubuntu-latest
    # This job depends on the 'build-and-push' job completing successfully
    needs: build-and-push
    # This job ONLY runs if the push was to the 'main' branch
    if: github.ref == 'refs/heads/main'

    permissions:
      id-token: write # Required for AWS OIDC authentication
      contents: read  # Required to checkout the repository

    steps:
      # 1. Checks out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configures AWS credentials using the OIDC role
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::643683863124:role/GH_ACTIONS # <-- REEMPLAZA CON TU ARN DE ROL
          aws-region: us-west-2 # Or your region variable

      # 3. Sets up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.15.0' # Specify a Helm version

      # 4. Configures kubectl to connect to the EKS cluster
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region us-west-2

      # 5. Deploys the application using Helm
      - name: Deploy application with Helm
        run: |
          helm upgrade --install hello-release ./helm-charts/hello-grainchain/ \
            --namespace default \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/hello-grainchain \
            --set image.tag=${{ github.sha }} \
            --wait